-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 16:16:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base_bousse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_bousse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_bousse` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `base_bousse` ;

-- -----------------------------------------------------
-- Table `base_bousse`.`OFF_2_contributeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_bousse`.`OFF_2_contributeur` (
  `pseudo` VARCHAR(254) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  PRIMARY KEY (`pseudo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;


-- -----------------------------------------------------
-- Table `base_bousse`.`OFF_2_pnns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_bousse`.`OFF_2_pnns` (
  `foodgroup1` VARCHAR(150) NOT NULL,
  `foodgroup2` VARCHAR(150) NOT NULL,
  `pnns1` VARCHAR(254) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `pnns2` VARCHAR(254) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  PRIMARY KEY (`pnns2`),
  UNIQUE INDEX `pnns2` (`pnns2` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;


-- -----------------------------------------------------
-- Table `base_bousse`.`OFF_2_version_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_bousse`.`OFF_2_version_produit` (
  `barcode` CHAR(13) NOT NULL,
  `date_creation_int` BIGINT NOT NULL,
  `date_creation` DATETIME NULL DEFAULT NULL,
  `date_modification_int` BIGINT NOT NULL,
  `date_modification` DATETIME NULL DEFAULT NULL,
  `pseudo` VARCHAR(254) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `pnns2` VARCHAR(254) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NULL DEFAULT NULL,
  `product_name` VARCHAR(254) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `nutrition_score_fr` TINYINT NULL DEFAULT NULL,
  `nutriscore_lettre` CHAR(1) NULL DEFAULT NULL,
  `nova_group` CHAR(1) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`barcode`, `date_modification_int`),
  INDEX `FK_pnns` (`pnns2` ASC) VISIBLE,
  INDEX `FK_contributeur_produit` (`pseudo` ASC) VISIBLE,
  CONSTRAINT `FK_pnns2`
    FOREIGN KEY (`pnns2`)
    REFERENCES `base_bousse`.`OFF_2_pnns` (`pnns2`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
